name: Issue Opened and Closed Comment

on:
  issues:
    types: [opened, closed]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Comment on Issue Opened
      if: ${{ github.event.action == 'opened' }}
      uses: actions-ecosystem/action-create-comment@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_number: ${{ github.event.issue.number }}
        body: |
          Thanks for opening this issue! We appreciate your contribution. Please make sure youâ€™ve provided all the necessary details and screenshots, and don't forget to follow our [Guidelines](https://github.com/OWNER/REPO/CONTRIBUTING.md) and Code of Conduct. Happy coding! ðŸš€
    - name: Comment on Issue Closed
      if: ${{ github.event.action == 'closed' }}
      uses: actions-ecosystem/action-create-comment@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_number: ${{ github.event.issue.number }}
        body: |
          This issue has been successfully closed. Thank you for your contribution and helping us improve the project! If you have any more ideas or run into other issues, feel free to open a new one. Happy coding! ðŸš€
